PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX hop:<http://something.org/>
PREFIX foaf:<http://xmlns.com/foaf/0.1/>



SELECT (?subject as ?Employés)
	WHERE { ?p0 rdfs:subClassOf <http://something.org/hopital_Employe#Employé> .
	        ?p1 rdfs:subClassOf ?p0 .
	        ?p2 rdf:type ?p1 .
	        ?p2 foaf:firstname ?subject .
	 }
