PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX hop:<http://something.org/>
PREFIX foaf:<http://xmlns.com/foaf/0.1/>
PREFIX foafbis:<http://something.org/hopital_patient#foaf:>



SELECT  (SUM(?date)as NombreDeConsultation)
WHERE {
    ?p2 foafbis:firstName "Alice" .
    ?p2 foafbis:lastName "Charles" .
    ?p3 hop:arring_date ?date .
}

